In [1]:
import pandas as pd
data = pd.read_csv("CarPrice_Assignment.csv")
data.drop(["car_ID", "symboling"], axis=1, inplace=True)
data["CarName"] = data["CarName"].map(lambda x: x.split()[0])
data["CarName"] = data["CarName"].replace({"maxda":"mazda",
                                           "porcshce":"porsche",
                                           "toyouta":"toyota",
                                           "vokswagen":"volkswagen",
                                           "vw":"volkswagen"
                                           })
cat_columns = data.select_dtypes(include='object').columns
from sklearn.preprocessing import LabelEncoder
my_encoder = LabelEncoder()

for column in cat_columns:
  if len(data[column].unique()) <= 3:
         data[column] = my_encoder.fit_transform(data[column])
data = pd.get_dummies(data,columns = data.select_dtypes(include='object').columns,
                      drop_first=True, dtype=int)

data.head()

/home/saponela/.cache/tmp/nix-shell-225884-1629305128/ipykernel_226440/3299546208.py:11: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_columns = data.select_dtypes(include='object').columns
/home/saponela/.cache/tmp/nix-shell-225884-1629305128/ipykernel_226440/3299546208.py:18: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  data = pd.get_dummies(data,columns = data.select_dtypes(include='object').columns,

,fueltype,aspiration,doornumber,drivewheel,enginelocation,wheelbase,carlength,carwidth,carheight,curbweight,...,cylindernumber_three,cylindernumber_twelve,cylindernumber_two,fuelsystem_2bbl,fuelsystem_4bbl,fuelsystem_idi,fuelsystem_mfi,fuelsystem_mpfi,fuelsystem_spdi,fuelsystem_spfi
0,1,0,1,2,0,88.6,168.8,64.1,48.8,2548,...,0,0,0,0,0,0,0,1,0,0
1,1,0,1,2,0,88.6,168.8,64.1,48.8,2548,...,0,0,0,0,0,0,0,1,0,0
2,1,0,1,2,0,94.5,171.2,65.5,52.4,2823,...,0,0,0,0,0,0,0,1,0,0
3,1,0,0,1,0,99.8,176.6,66.2,54.3,2337,...,0,0,0,0,0,0,0,1,0,0
4,1,0,0,0,0,99.4,176.6,66.4,54.3,2824,...,0,0,0,0,0,0,0,1,0,0

In [2]:
import statsmodels.api as sm
y = data['price']
X = data.drop('price', axis=1)
X = sm.add_constant(X)
model = sm.OLS(endog=y, exog = X).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.966
Model:                            OLS   Adj. R-squared:                  0.952
Method:                 Least Squares   F-statistic:                     70.05
Date:                Tue, 20 Oct 2026   Prob (F-statistic):           1.14e-82
Time:                        13:53:44   Log-Likelihood:                -1785.6
No. Observations:                 205   AIC:                             3691.
Df Residuals:                     145   BIC:                             3891.
Df Model:                          59
Covariance Type:            nonrobust
=========================================================================================
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
const                 -9.737e+12   7.02e+12     -1.387      0.168   -2.36e+13    4.14e+12
fueltype               9.737e+12   7.02e+12      1.387      0.168   -4.14e+12    2.36e+13
aspiration             1781.7638    800.452      2.226      0.028     199.703    3363.825
doornumber             -283.1150    455.086     -0.622      0.535   -1182.573     616.343
drivewheel              212.1955    547.647      0.387      0.699    -870.207    1294.598
enginelocation         6610.5357   1920.839      3.441      0.001    2814.075    1.04e+04
wheelbase               256.5619     87.147      2.944      0.004      84.319     428.805
carlength              -138.9979     48.509     -2.865      0.005    -234.874     -43.122
carwidth                680.9620    217.931      3.125      0.002     250.230    1111.694
carheight              -265.6923    136.994     -1.939      0.054    -536.456       5.071
curbweight                6.2393      1.529      4.080      0.000       3.217       9.262
enginesize               92.0641     24.531      3.753      0.000      43.581     140.548
boreratio             -3395.0363   1833.506     -1.852      0.066   -7018.888     228.815
stroke                -1168.7170    985.871     -1.185      0.238   -3117.251     779.817
compressionratio       -847.8002    484.402     -1.750      0.082   -1805.202     109.602
horsepower                0.1216     23.521      0.005      0.996     -46.367      46.610
peakrpm                   2.3517      0.643      3.659      0.000       1.082       3.622
citympg                  -4.3645    133.606     -0.033      0.974    -268.431     259.702
highwaympg              102.8820    113.789      0.904      0.367    -122.018     327.782
CarName_alfa-romero    3958.6556   2463.332      1.607      0.110    -910.021    8827.332
CarName_audi           3734.3539   2316.701      1.612      0.109    -844.512    8313.220
CarName_bmw            9147.8403   2215.819      4.128      0.000    4768.363    1.35e+04
CarName_buick          5581.1454   2730.761      2.044      0.043     183.907     1.1e+04
CarName_chevrolet     -1350.7433   2294.403     -0.589      0.557   -5885.539    3184.052
CarName_dodge         -2176.8936   2024.273     -1.075      0.284   -6177.787    1823.999
CarName_honda           713.2609   2267.747      0.315      0.754   -3768.850    5195.372
CarName_isuzu           392.5929   2160.190      0.182      0.856   -3876.936    4662.121
CarName_jaguar         1965.9658   3212.490      0.612      0.542   -4383.391    8315.323
CarName_mazda           959.2508   1913.422      0.501      0.617   -2822.551    4741.052
CarName_mercury         -91.9881   2899.981     -0.032      0.975   -5823.684    5639.708
CarName_mitsubishi    -2674.5354   2017.052     -1.326      0.187   -6661.158    1312.087
CarName_nissan          500.5992   1866.160      0.268      0.789   -3187.790    4188.988
CarName_peugeot       -2401.1904   2288.585     -1.049      0.296   -6924.485    2122.104
CarName_plymouth      -2150.7173   2039.139     -1.055      0.293   -6180.993    1879.559
CarName_porsche        6694.2667   2894.221      2.313      0.022     973.956    1.24e+04
CarName_renault        -453.3983   2408.728     -0.188      0.851   -5214.152    4307.355
CarName_saab           4299.3328   2210.480      1.945      0.054     -69.592    8668.257
CarName_subaru        -2516.6281   1786.527     -1.409      0.161   -6047.626    1014.369
CarName_toyota           38.9504   1914.921      0.020      0.984   -3745.814    3823.715
CarName_volkswagen      872.6451   1943.234      0.449      0.654   -2968.077    4713.368
CarName_volvo          1413.5172   2160.141      0.654      0.514   -2855.914    5682.948
carbody_hardtop       -2128.5869   1161.384     -1.833      0.069   -4424.015     166.841
carbody_hatchback     -2929.1850   1085.644     -2.698      0.008   -5074.916    -783.454
carbody_sedan         -2198.8910   1158.265     -1.898      0.060   -4488.156      90.374
carbody_wagon         -2457.6750   1264.407     -1.944      0.054   -4956.725      41.375
enginetype_dohcv      -3807.2030   4645.861     -0.819      0.414    -1.3e+04    5375.154
enginetype_l            636.5992   1629.165      0.391      0.697   -2583.379    3856.577
enginetype_ohc          909.9933   1195.162      0.761      0.448   -1452.197    3272.183
enginetype_ohcf        4094.7688   1191.532      3.437      0.001    1739.754    6449.783
enginetype_ohcv       -2510.2464   1224.204     -2.051      0.042   -4929.836     -90.657
enginetype_rotor       2273.5612   2214.953      1.026      0.306   -2104.203    6651.325
cylindernumber_five   -5546.4419   2836.448     -1.955      0.052   -1.12e+04      59.683
cylindernumber_four   -2651.1388   3493.391     -0.759      0.449   -9555.685    4253.408
cylindernumber_six    -3137.2500   2647.764     -1.185      0.238   -8370.447    2095.947
cylindernumber_three   3037.7520   2929.161      1.037      0.301   -2751.615    8827.119
cylindernumber_twelve -3537.5167   5075.730     -0.697      0.487   -1.36e+04    6494.458
cylindernumber_two     2273.5640   2214.953      1.026      0.306   -2104.200    6651.328
fuelsystem_2bbl        2376.4744   1469.914      1.617      0.108    -528.751    5281.700
fuelsystem_4bbl        -517.5618   2539.241     -0.204      0.839   -5536.268    4501.144
fuelsystem_idi         9.737e+12   7.02e+12      1.387      0.168   -4.14e+12    2.36e+13
fuelsystem_mfi         -368.9240   2567.093     -0.144      0.886   -5442.680    4704.832
fuelsystem_mpfi        1315.1754   1559.579      0.843      0.400   -1767.269    4397.619
fuelsystem_spdi         495.8075   1796.042      0.276      0.783   -3053.998    4045.613
fuelsystem_spfi        1580.7470   2669.968      0.592      0.555   -3696.336    6857.830
==============================================================================
Omnibus:                       62.411   Durbin-Watson:                   1.666
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              281.977
Skew:                           1.099   Prob(JB):                     5.88e-62
Kurtosis:                       8.309   Cond. No.                     1.00e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 6.73e-23. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

/home/saponela/.cache/tmp/nix-shell-225884-1629305128/ipykernel_226440/636390705.py:5: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  model = sm.OLS(endog=y, exog = X).fit()

In [4]:
selected_data = data[['price', 'fueltype', 'aspiration', 'enginelocation', 'curbweight']]
selected_data.head()

     price  fueltype  aspiration  enginelocation  curbweight
0  13495.0         1           0               0        2548
1  16500.0         1           0               0        2548
2  16500.0         1           0               0        2823
3  13950.0         1           0               0        2337
4  17450.0         1           0               0        2824

In [7]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

NameError: name 'X_train' is not defined

In [8]:
y = selected_data['price'].values
X = selected_data.drop('price', axis=1).values
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
from sklearn.linear_model import LinearRegression
model1 = LinearRegression()
model1.fit(X_train, y_train)
print(model1.score(X_test, y_test))

NameError: name 'selected_data' is not defined

In [7]:
from yellowbrick.regressor import ResidualsPlot

visualizer = ResidualsPlot(model1)
visualizer.fit(X_train, y_train)
visualizer.score(X_test, y_test)
visualizer.show()

NameError: name 'model1' is not defined